# Generated by Django 5.1 on 2024-10-19 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Cost1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, null=True)),
                ('program_duration', models.CharField(max_length=255)),
                ('program_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='CS_Fees1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('sum_of', models.CharField(max_length=200)),
                ('paid_for', models.CharField(default='Tuition Fees', max_length=200)),
                ('check_no', models.BigIntegerField(blank=True, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.CharField(choices=[('First Year', 'First Year')], max_length=20)),
                ('payment_date', models.DateField(null=True)),
                ('second_payment_date', models.DateField(blank=True, null=True)),
                ('paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_slip', models.FileField(blank=True, null=True, upload_to='payment_slips/')),
                ('second_payment_slip', models.FileField(blank=True, null=True, upload_to='payment_slips/')),
                ('payment_status', models.CharField(choices=[('Paid Full', 'Paid Full'), ('Incomplete Fees', 'Incomplete Fees')], max_length=20)),
                ('cost_of_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_program_payments', to='app.cs_cost1')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs')),
                ('program_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_details_payments', to='app.programs')),
            ],
        ),
        migrations.CreateModel(
            name='CS_Cost4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, null=True)),
                ('program_duration', models.PositiveIntegerField()),
                ('program_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('all_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs')),
            ],
        ),
        migrations.CreateModel(
            name='CS_Cost3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, null=True)),
                ('program_duration', models.PositiveIntegerField()),
                ('program_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('all_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs')),
            ],
        ),
        migrations.CreateModel(
            name='CS_Cost2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, null=True)),
                ('program_duration', models.PositiveIntegerField()),
                ('program_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('all_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs')),
            ],
        ),
        migrations.AddField(
            model_name='cs_cost1',
            name='all_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(blank=True, upload_to='profiles/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs')),
            ],
        ),
    ]
