# Generated by Django 5.1 on 2024-11-09 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cs_fees4'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('year_one_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_one_payment_date', models.DateField(blank=True, null=True)),
                ('year_one_paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_one_payment_slip', models.FileField(blank=True, null=True, upload_to='payment_slips/')),
                ('year_two_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_two_payment_date', models.DateField(blank=True, null=True)),
                ('year_two_paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_two_payment_slip', models.FileField(blank=True, null=True, upload_to='payment_slips/')),
                ('year_three_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_three_payment_date', models.DateField(blank=True, null=True)),
                ('year_three_paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_three_payment_slip', models.FileField(blank=True, null=True, upload_to='payment_slips/')),
                ('year_four_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_four_payment_date', models.DateField(blank=True, null=True)),
                ('year_four_paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year_four_payment_slip', models.FileField(blank=True, null=True, upload_to='payment_slips/')),
                ('year_one_status', models.CharField(blank=True, choices=[('Paid Full', 'Paid Full'), ('Incomplete Fees', 'Incomplete Fees')], max_length=20, null=True)),
                ('year_two_status', models.CharField(blank=True, choices=[('Paid Full', 'Paid Full'), ('Incomplete Fees', 'Incomplete Fees')], max_length=20, null=True)),
                ('year_three_status', models.CharField(blank=True, choices=[('Paid Full', 'Paid Full'), ('Incomplete Fees', 'Incomplete Fees')], max_length=20, null=True)),
                ('year_four_status', models.CharField(blank=True, choices=[('Paid Full', 'Paid Full'), ('Incomplete Fees', 'Incomplete Fees')], max_length=20, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programs')),
            ],
        ),
    ]
