# Generated by Django 5.1 on 2024-11-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_studentfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='CS_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Paid Full', 'Paid Full'), ('Incomplete', 'Incomplete')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentFees',
        ),
    ]
